services:
  api:
  image: nomeimagem #docker build -t nomeimagem
  ports:
    - "8080:8080"
  depends_on:
    - db
  
  db:
    image: postgres:latest #especificar banco e versão, caso necessário
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: aula-teste


#especificar db no arquivo .properties
#docker-compose up -d